DROP DATABASE IF EXISTS bank;
CREATE DATABASE bank;
USE bank;
CREATE TABLE accounts (
    id INT PRIMARY KEY AUTO_INCREMENT,
    account_owner VARCHAR(100) NOT NULL,
    password INT NOT NULL,
    balance DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
